#!/bin/sh
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"
setupenvironment
configarchitecture 'amd64'

insertinstalledpackage 'meta' 'all' '1' 'Depends: oldname'
insertinstalledpackage 'oldrec' 'all' '1'
insertinstalledpackage 'instrec' 'all' '1'
insertinstalledpackage 'libsame1' 'amd64' '1' 'Source: samelib
Recommends: oldrec, instrec, unsatrec
Multi-Arch: same'
insertinstalledpackage 'oldname' 'all' '1' 'Depends: libsame1
Recommends: oldrec, instrec, unsatrec'

insertpackage 'unstable' 'meta' 'all' '2' 'Depends: newname'
insertpackage 'unstable' 'libsame2' 'amd64' '2' 'Source: samelib
Recommends: instrec, unsatrec, newrec
Multi-Arch: same'
insertpackage 'unstable' 'newname' 'all' '2' 'Depends: libsame2
Conflicts: oldname (<< 2)
Replaces: oldname (<< 2)
Provides: oldname (= 2)
Recommends: instrec, unsatrec, newrec'
insertpackage 'unstable' 'oldrec' 'all' '2'
insertpackage 'unstable' 'instrec' 'all' '2'
insertpackage 'unstable' 'unsatrec' 'all' '2'
insertpackage 'unstable' 'newrec' 'all' '2'

insertpackage 'experimental' 'oldname' 'all' '2' 'Depends: newname' '' 'oldlibs'

setupaptarchive

testsuccess aptmark auto oldrec libsame1

testsuccessequal "Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages were automatically installed and are no longer required:
  libsame1 oldrec
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  libsame2 newname newrec
The following packages will be upgraded:
  instrec meta oldname oldrec
4 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Inst instrec [1] (2 unstable [all])
Inst libsame2 (2 unstable [amd64])
Inst oldname [1] (2 experimental [all]) []
Inst newname (2 unstable [all])
Inst meta [1] (2 unstable [all])
Inst newrec (2 unstable [all])
Inst oldrec [1] (2 unstable [all])
Conf instrec (2 unstable [all])
Conf libsame2 (2 unstable [amd64])
Conf oldname (2 experimental [all])
Conf newname (2 unstable [all])
Conf meta (2 unstable [all])
Conf newrec (2 unstable [all])
Conf oldrec (2 unstable [all])" apt full-upgrade -st experimental

testsuccessequal "Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages were automatically installed and are no longer required:
  libsame1 oldrec
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  oldname
The following NEW packages will be installed:
  libsame2 newname newrec
The following packages will be upgraded:
  instrec meta oldrec
3 upgraded, 3 newly installed, 1 to remove and 0 not upgraded.
Inst libsame2 (2 unstable [amd64])
Inst meta [1] (2 unstable [all]) []
Remv oldname [1] []
Inst newname (2 unstable [all])
Inst instrec [1] (2 unstable [all])
Inst newrec (2 unstable [all])
Inst oldrec [1] (2 unstable [all])
Conf libsame2 (2 unstable [amd64])
Conf meta (2 unstable [all])
Conf newname (2 unstable [all])
Conf instrec (2 unstable [all])
Conf newrec (2 unstable [all])
Conf oldrec (2 unstable [all])" aptget full-upgrade -s
