#!/bin/sh
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"
setupenvironment
configarchitecture 'amd64'

insertinstalledpackage 'oldrec' 'all' '1'
insertinstalledpackage 'instrec' 'all' '1'
insertpackage 'unstable' 'newrec' 'all' '1'

OLDDEPENDS=''
NEWDEPENDS=''
librarybump() {
	insertpackage 'unstable' "unsatrec-$1" 'all' '1'
	insertinstalledpackage "$1$2" 'amd64' '1' "Source: library-source
Recommends: oldrec, instrec, unsatrec-$1 $4
Multi-Arch: same"
	insertpackage 'unstable' "$1$3" 'amd64' '2' "Source: library-source
Recommends: instrec, unsatrec-$1, newrec $4
Multi-Arch: same"
	if [ -n "$OLDDEPENDS" ]; then
		OLDDEPENDS="$OLDDEPENDS, $1$2"
	else
		OLDDEPENDS="$1$2"
	fi
	if [ -n "$NEWDEPENDS" ]; then
		NEWDEPENDS="$NEWDEPENDS, $1$3"
	else
		NEWDEPENDS="$1$3"
	fi
}
librarybump 'libsame' '1' '2'
librarybump 'libdota' '1.1' '1.2000'
librarybump 'libdotb' '1.1' '2000.1'
librarybump 'libdotc' '1.1' '2.1'
librarybump 'libdotd' '1.1000' '2.1'
librarybump 'libdasha' '1-1' '1-2000'
librarybump 'libdashb' '1-1' '2000-1'
librarybump 'libdashc' '1-1' '2-1'
librarybump 'libdashd' '1-1000' '2-1'
librarybump 'libtimea' '1' '1t64'
librarybump 'libtimeb' '1' '2'
librarybump 'libdevela' '1-dev' '2-dev'
librarybump 'libdevelb' '1-dev' '10-dev'
librarybump 'libdevelc' '1.1-dev' '2-dev'
librarybump 'libdeveld' '1.1-dev' '2.10-dev'
librarybump 'libfoo' '1abiv5' '2'
librarybump 'libbar' '1' '2abiv5'

insertpackage 'unstable' 'unsatrec-pulse' 'all' '1'
insertpackage 'unstable' 'unsatrec-alsa' 'all' '1'
librarybump 'libsound' '-pulse-1' '-pulse-2' ', unsatrec-pulse'
librarybump 'libsound' '-alsa-1' '-alsa-2' ', unsatrec-alsa'

insertinstalledpackage 'libsound-pulse-0' 'amd64' '0' 'Source: library-source
Recommends: instrec
Multi-Arch: same'
insertinstalledpackage 'libsound-alsa-0' 'amd64' '0' 'Source: library-source
Recommends: instrec
Multi-Arch: same'
insertpackage 'experimental' 'libsound-pulse-3' 'amd64' '3' 'Source: library-source
Recommends: instrec, unsatrec-libsound, newrec, unsatrec-exp
Multi-Arch: same'
insertpackage 'experimental' 'libsound-alsa-3' 'amd64' '3' 'Source: library-source
Recommends: instrec, unsatrec-libsound, newrec, unsatrec-exp
Multi-Arch: same'

insertinstalledpackage 'foo' 'all' '1' "Depends: $OLDDEPENDS"
insertpackage 'unstable' 'foo' 'all' '2' "Depends: $NEWDEPENDS"

setupaptarchive

testsuccess aptmark auto oldrec instrec 'lib*'

testsuccessequal "Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages were automatically installed and are no longer required:
  libbar1 libdasha1-1 libdashb1-1 libdashc1-1 libdashd1-1000 libdevela1-dev
  libdevelb1-dev libdevelc1.1-dev libdeveld1.1-dev libdota1.1 libdotb1.1
  libdotc1.1 libdotd1.1000 libfoo1abiv5 libsame1 libsound-alsa-0
  libsound-alsa-1 libsound-pulse-0 libsound-pulse-1 libtimea1 libtimeb1 oldrec
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  libbar2abiv5 libdasha1-2000 libdashb2000-1 libdashc2-1 libdashd2-1
  libdevela2-dev libdevelb10-dev libdevelc2-dev libdeveld2.10-dev
  libdota1.2000 libdotb2000.1 libdotc2.1 libdotd2.1 libfoo2 libsame2
  libsound-alsa-2 libsound-pulse-2 libtimea1t64 libtimeb2 newrec
The following packages will be upgraded:
  foo
1 upgraded, 20 newly installed, 0 to remove and 0 not upgraded.
Inst libsame2 (2 unstable [amd64])
Inst libdota1.2000 (2 unstable [amd64])
Inst libdotb2000.1 (2 unstable [amd64])
Inst libdotc2.1 (2 unstable [amd64])
Inst libdotd2.1 (2 unstable [amd64])
Inst libdasha1-2000 (2 unstable [amd64])
Inst libdashb2000-1 (2 unstable [amd64])
Inst libdashc2-1 (2 unstable [amd64])
Inst libdashd2-1 (2 unstable [amd64])
Inst libtimea1t64 (2 unstable [amd64])
Inst libtimeb2 (2 unstable [amd64])
Inst libdevela2-dev (2 unstable [amd64])
Inst libdevelb10-dev (2 unstable [amd64])
Inst libdevelc2-dev (2 unstable [amd64])
Inst libdeveld2.10-dev (2 unstable [amd64])
Inst libfoo2 (2 unstable [amd64])
Inst libbar2abiv5 (2 unstable [amd64])
Inst libsound-pulse-2 (2 unstable [amd64])
Inst libsound-alsa-2 (2 unstable [amd64])
Inst foo [1] (2 unstable [all])
Inst newrec (1 unstable [all])
Conf libsame2 (2 unstable [amd64])
Conf libdota1.2000 (2 unstable [amd64])
Conf libdotb2000.1 (2 unstable [amd64])
Conf libdotc2.1 (2 unstable [amd64])
Conf libdotd2.1 (2 unstable [amd64])
Conf libdasha1-2000 (2 unstable [amd64])
Conf libdashb2000-1 (2 unstable [amd64])
Conf libdashc2-1 (2 unstable [amd64])
Conf libdashd2-1 (2 unstable [amd64])
Conf libtimea1t64 (2 unstable [amd64])
Conf libtimeb2 (2 unstable [amd64])
Conf libdevela2-dev (2 unstable [amd64])
Conf libdevelb10-dev (2 unstable [amd64])
Conf libdevelc2-dev (2 unstable [amd64])
Conf libdeveld2.10-dev (2 unstable [amd64])
Conf libfoo2 (2 unstable [amd64])
Conf libbar2abiv5 (2 unstable [amd64])
Conf libsound-pulse-2 (2 unstable [amd64])
Conf libsound-alsa-2 (2 unstable [amd64])
Conf foo (2 unstable [all])
Conf newrec (1 unstable [all])" apt full-upgrade -s #-o Debug::pkgDepCache::AutoInstall=1
