#!/bin/sh
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"
setupenvironment
configarchitecture 'amd64'

insertinstalledpackage 'oldrec' 'all' '1'
insertinstalledpackage 'instrec' 'all' '1'
insertpackage 'unstable' 'newrec' 'all' '1'

OLDDEPENDS=''
NEWDEPENDS=''
librarybump() {
	insertpackage 'unstable' "unsatrec-$1" 'all' '1'
	insertinstalledpackage "$1$2" 'amd64' '1' "Source: library-source
Recommends: oldrec, instrec, unsatrec-$1 $4
Multi-Arch: same"
	insertpackage 'unstable' "$1$3" 'amd64' '2' "Source: library-source
Recommends: instrec, unsatrec-$1, newrec $4
Multi-Arch: same"
	if [ -n "$OLDDEPENDS" ]; then
		OLDDEPENDS="$OLDDEPENDS, $1$2"
	else
		OLDDEPENDS="$1$2"
	fi
	if [ -n "$NEWDEPENDS" ]; then
		NEWDEPENDS="$NEWDEPENDS, $1$3"
	else
		NEWDEPENDS="$1$3"
	fi
}
librarybump 'libsame' '1' '2'
librarybump 'libdota' '1.1' '1.2000'
librarybump 'libdotb' '1.1' '2000.1'
librarybump 'libdotc' '1.1' '2.1'
librarybump 'libdotd' '1.1000' '2.1'
librarybump 'libdasha' '1-1' '1-2000'
librarybump 'libdashb' '1-1' '2000-1'
librarybump 'libdashc' '1-1' '2-1'
librarybump 'libdashd' '1-1000' '2-1'
librarybump 'libtimea' '1' '1t64'
librarybump 'libtimeb' '1' '2'
librarybump 'libdevela' '1-dev' '2-dev'
librarybump 'libdevelb' '1-dev' '10-dev'
librarybump 'libdevelc' '1.1-dev' '2-dev'
librarybump 'libdeveld' '1.1-dev' '2.10-dev'
librarybump 'libfoo' '1abiv5' '2'
librarybump 'libbar' '1' '2abiv5'

insertpackage 'unstable' 'unsatrec-pulse' 'all' '1'
insertpackage 'unstable' 'unsatrec-alsa' 'all' '1'
librarybump 'libsound' '-pulse-1' '-pulse-2' ', unsatrec-pulse'
librarybump 'libsound' '-alsa-1' '-alsa-2' ', unsatrec-alsa'

insertinstalledpackage 'libsound-pulse-0' 'amd64' '0' 'Source: library-source
Recommends: instrec
Multi-Arch: same'
insertinstalledpackage 'libsound-alsa-0' 'amd64' '0' 'Source: library-source
Recommends: instrec
Multi-Arch: same'
insertpackage 'experimental' 'libsound-pulse-3' 'amd64' '3' 'Source: library-source
Recommends: instrec, unsatrec-libsound, newrec, unsatrec-exp
Multi-Arch: same'
insertpackage 'experimental' 'libsound-alsa-3' 'amd64' '3' 'Source: library-source
Recommends: instrec, unsatrec-libsound, newrec, unsatrec-exp
Multi-Arch: same'

insertinstalledpackage 'foo' 'all' '1' "Depends: $OLDDEPENDS"
insertpackage 'unstable' 'foo' 'all' '2' "Depends: $NEWDEPENDS"

setupaptarchive

testsuccess aptmark auto oldrec instrec 'lib*'

testsuccess apt full-upgrade -s
testfailureequal "Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages were automatically installed and are no longer required:
   libbar1 (1, replaced by libbar2abiv5)
   libdasha1-1 (1, replaced by libdasha1-2000)
   libdashb1-1 (1, replaced by libdashb2000-1)
   libdashc1-1 (1, replaced by libdashc2-1)
   libdashd1-1000 (1, replaced by libdashd2-1)
   libdevela1-dev (1, replaced by libdevela2-dev)
   libdevelb1-dev (1, replaced by libdevelb10-dev)
   libdevelc1.1-dev (1, replaced by libdevelc2-dev)
   libdeveld1.1-dev (1, replaced by libdeveld2.10-dev)
   libdota1.1 (1, replaced by libdota1.2000)
   libdotb1.1 (1, replaced by libdotb2000.1)
   libdotc1.1 (1, replaced by libdotc2.1)
   libdotd1.1000 (1, replaced by libdotd2.1)
   libfoo1abiv5 (1, replaced by libfoo2)
   libsame1 (1, replaced by libsame2)
   libsound-alsa-0 (0, replaced by libsound-alsa-2)
   libsound-alsa-1 (1, replaced by libsound-alsa-2)
   libsound-pulse-0 (0, replaced by libsound-pulse-2)
   libsound-pulse-1 (1, replaced by libsound-pulse-2)
   libtimea1 (1, replaced by libtimea1t64)
   libtimeb1 (1, replaced by libtimeb2)
   oldrec (1)
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
   libbar2abiv5 (2)
   libdasha1-2000 (2)
   libdashb2000-1 (2)
   libdashc2-1 (2)
   libdashd2-1 (2)
   libdevela2-dev (2)
   libdevelb10-dev (2)
   libdevelc2-dev (2)
   libdeveld2.10-dev (2)
   libdota1.2000 (2)
   libdotb2000.1 (2)
   libdotc2.1 (2)
   libdotd2.1 (2)
   libfoo2 (2)
   libsame2 (2)
   libsound-alsa-2 (2)
   libsound-pulse-2 (2)
   libtimea1t64 (2)
   libtimeb2 (2)
   newrec (1)
The following packages will be upgraded:
   foo (1 => 2)
1 upgraded, 20 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/882 B of archives.
After this operation, 860 kB of additional disk space will be used.
E: Trivial Only specified but this is not a trivial operation." apt full-upgrade -V --trivial-only
