#!/bin/sh
#
# this is a regression test for LP: #1445239 where a partial download can
# trigger an endless hang of the download method
#

set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"
setupenvironment
configarchitecture 'amd64'

changetowebserver

TESTFILE='aptarchive/testfile'
truncate -s 100k $TESTFILE

DOWNLOADLOG='rootdir/tmp/testdownloadfile.log'

TARGET=./downloaded/testfile-downloaded
truncate -s 99k $TARGET
if ! downloadfile http://localhost:${APTHTTPPORT}/testfile "$TARGET" > "$DOWNLOADLOG"; then
    cat >&2 "$DOWNLOADLOG"
    msgfail
else
    msgpass
fi
