#!/bin/sh
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"
setupenvironment
configarchitecture 'amd64'

insertpackage 'buster' 'unrelated' 'all' '1'

getsuitefromreleasefile() { echo -n 'stable'; }
getcodenamefromsuite() { echo -n 'buster'; }
setupaptarchive --no-update
testsuccess aptget update

cp -a aptarchive/dists aptarchive/dists.bak
cp -a rootdir/var/lib/apt/lists rootdir/var/lib/apt/lists.bak
APTARCHIVE="$(readlink -f './aptarchive')"
sed -i -e 's#^Suite: stable#Suite: oldstable#' $(find ./aptarchive -name 'Release')
signreleasefiles
testfailuremsg "E: Repository 'file:$APTARCHIVE buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
N: These changes can be acknowledged interactively with 'apt' or with --allow-releaseinfo-change." apt update

sed -i -e '/^Codename: / a\
Future-Suite: testing' $(find ./rootdir/var/lib/apt/lists -name '*Release')
testfailuremsg "E: Repository 'file:$APTARCHIVE buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
N: These changes can be acknowledged interactively with 'apt' or with --allow-releaseinfo-change." apt update

sed -i -e 's#Future-Suite: testing#Future-Suite: oldstable#' $(find ./rootdir/var/lib/apt/lists -name '*Release')
testfailuremsg "E: Repository 'file:$APTARCHIVE buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
N: These changes can be acknowledged interactively with 'apt' or with --allow-releaseinfo-change." apt update -o Acquire::AllowReleaseInfoChangeIfAnnounced::Suite=0

testsuccesswithnotice apt update
testequal "All packages are up to date.
N: Repository 'file:$APTARCHIVE buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'" tail -n 2 rootdir/tmp/testsuccesswithnotice.output

sed -i -e '/^Codename: / a\
Future-Suite: oldoldstable' $(find ./aptarchive -name 'Release')
signreleasefiles
testsuccesswithnotice apt update
testequal "All packages are up to date.
N: Repository 'file:$APTARCHIVE buster InRelease' changes its 'Suite' value from 'oldstable' to 'oldoldstable' soon." tail -n 2 rootdir/tmp/testsuccesswithnotice.output

sed -i -e '/^Codename: / a\
Future-Release-Notes: https://example.org/future' $(find ./aptarchive -name 'Release')
signreleasefiles
testsuccesswithnotice apt update
testequal "All packages are up to date.
N: Repository 'file:$APTARCHIVE buster InRelease' changes its 'Suite' value from 'oldstable' to 'oldoldstable' soon.
N: More information about this can be found online in the Release notes at: https://example.org/future" tail -n 3 rootdir/tmp/testsuccesswithnotice.output
